
on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - '/**'
      - '!**.md'
      - '!.gitingore'
  workflow_dispatch:


name: Build and Push Docker Container Image
jobs:
  build-and-push-docker-image:
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository (${{github.event.repository.name}})
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) from (lorawan-gateway-sx1302)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository_owner}}/${{github.event.repository.name}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=${{github.event.repository.name}}
            org.opencontainers.image.description=This Image Containes funcionality to run a LoRaWAN Gateway
            org.opencontainers.image.url=ghcr.io/${{github.repository_owner}}/${{github.event.repository.name}}
      - name: Build and push Dockerimage
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags }}
          labels: ${{steps.meta.outputs.labels }}
          annotations: ${{steps.meta.outputs.annotations}}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=This Image Containes funcionality to run a LoRaWAN Gateway
      - name: delte old packages (lorawan-gateway-sx1302)
        uses: actions/delete-package-versions@v5
        with:
          owner: '${{github.repository_owner}}'
          package-name: '${{github.event.repository.name}}'
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'
