
on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - '/**'
      - '!**.md'
      - '!.gitingore'
  workflow_dispatch:

name: Build and Push lorawan gateway

jobs:
  build-and-push:
    uses: Pascal0030/.github/workflows/build-and-push-docker-container.yaml@main
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      registry: ghcr.io
      docker-image-name: lorawan-gateway-sx1302
      docker-image-description: This Image Containes funcionality to run a LoRaWAN Gateway
